name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build static files
        run: |
          mkdir -p public
          cp -r web/static/* public/
          cp web/templates/index.html public/index.html
          cp web/templates/login.html public/login.html
          cp web/templates/admin.html public/admin.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public