name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - uses: actions/jekyll-build-pages@v1
      with:
        source: ./
        destination: ./_site
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: github-pages
        path: ./_site
        if-no-files-found: error
